import type { Product, ToolRec } from "./types";

/**
 * General tool discovery: given ANY goal ("a tool to design premium UI", "add auth",
 * "send email"), ask the LLM for the single best-fit SaaS/MCP tool and return a ToolRec
 * the app can render as a card. This is a recommendation layer (not Shopify catalogue
 * data), so it is LLM-generated by design; it returns a real vendor + pricing URL.
 */

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const clean = (s: unknown, fallback = ""): string => (typeof s === "string" && s.trim() ? s.trim().replace(/\s*[—–]\s*/g, ", ") : fallback);

const KEY = () => process.env.OPENROUTER_API_KEY || process.env.OPENROUTER_INFRA_KEY;
const MODEL = () => process.env.AISLE_CHAT_MODEL || "deepseek/deepseek-chat-v3.1";

async function chatJson(prompt: string, maxTokens: number): Promise<string | null> {
  const key = KEY();
  if (!key) return null;
  try {
    const resp = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json", "HTTP-Referer": "https://aisle.dev", "X-Title": "Aisle" },
      body: JSON.stringify({ model: MODEL(), max_tokens: maxTokens, temperature: 0.5, messages: [{ role: "user", content: prompt }] }),
      signal: AbortSignal.timeout(18000),
    });
    if (!resp.ok) return null;
    const data = (await resp.json()) as { choices?: Array<{ message?: { content?: unknown } }> };
    const c = data.choices?.[0]?.message?.content;
    return typeof c === "string" ? c : null;
  } catch {
    return null;
  }
}

/**
 * Complementary tools to pair with a SaaS purchase (e.g. an email API, also a domain and
 * an analytics tool). Returned as saas: "products" so they render as checkout complements.
 */
export async function complementTools(product: Product): Promise<Product[]> {
  const name = product.title.replace(/\s+(plan|pro|standard|starter|grow)\b/gi, "").trim() || product.title;
  const raw = await chatJson(
    `A developer is buying "${product.title}". Suggest 2 DIFFERENT complementary tools/SaaS that pair well with ${name} in a real stack (not competitors, not the same tool). ` +
      `For each give a short name, one-word category, and an approximate US price per month in whole dollars (0 if free). ` +
      `Return ONLY minified JSON: [{"tool":"","category":"","price_usd":0},{"tool":"","category":"","price_usd":0}]`,
    200,
  );
  if (!raw) return [];
  const s = raw.indexOf("["), e = raw.lastIndexOf("]");
  if (s < 0 || e < s) return [];
  try {
    const arr = JSON.parse(raw.slice(s, e + 1)) as unknown[];
    const seen = new Set<string>([product.sku]);
    const out: Product[] = [];
    for (const el of arr.slice(0, 3)) {
      if (!el || typeof el !== "object") continue;
      const o = el as Record<string, unknown>;
      const tool = clean(o["tool"]);
      if (!tool) continue;
      const sku = `saas:${slug(tool)}`;
      if (seen.has(sku)) continue;
      seen.add(sku);
      const price = typeof o["price_usd"] === "number" && Number.isFinite(o["price_usd"]) ? Math.max(0, Math.round(o["price_usd"])) : 0;
      out.push({
        sku,
        title: `${tool} plan`,
        priceMinor: price * 100,
        currency: "USD",
        merchantId: slug(tool),
        image: "",
        tone: "expert",
        pitch: clean(o["category"], "pairs well with your stack"),
        attrs: ["saas"],
      });
    }
    return out;
  } catch {
    return [];
  }
}

export async function recommendTool(goal: string): Promise<ToolRec | null> {
  const key = process.env.OPENROUTER_API_KEY || process.env.OPENROUTER_INFRA_KEY;
  if (!key) return null;
  const model = process.env.AISLE_CHAT_MODEL || "deepseek/deepseek-chat-v3.1";
  const prompt =
    `A developer wants a SaaS or MCP tool for this goal: "${goal}".\n` +
    `Recommend the SINGLE best-fit, widely-used, reputable tool. Prefer ones with an official MCP server or clean API.\n` +
    `Give its canonical public pricing or checkout URL (a real https URL, no tracking params). Name a sensible starting paid plan and its approximate US price per month in whole dollars (use 0 if it is free or you are unsure). List 2 alternatives. No em dashes.\n` +
    `Return ONLY minified JSON: {"tool_name":"","category":"","checkout_url":"https://...","plan":"","price_usd":0,"has_mcp":true,"why":"<=20 words","alternatives":[{"tool_name":"","why":"<=10 words"},{"tool_name":"","why":"<=10 words"}]}`;
  try {
    const resp = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json", "HTTP-Referer": "https://aisle.dev", "X-Title": "Aisle" },
      body: JSON.stringify({ model, max_tokens: 380, temperature: 0.5, messages: [{ role: "user", content: prompt }] }),
      signal: AbortSignal.timeout(22000),
    });
    if (!resp.ok) return null;
    const data = (await resp.json()) as { choices?: Array<{ message?: { content?: unknown } }> };
    const c = data.choices?.[0]?.message?.content;
    if (typeof c !== "string") return null;
    const s = c.indexOf("{"), e = c.lastIndexOf("}");
    if (s < 0 || e < s) return null;
    const o = JSON.parse(c.slice(s, e + 1)) as Record<string, unknown>;
    const toolName = clean(o["tool_name"]);
    if (!toolName) return null;
    let checkoutUrl = clean(o["checkout_url"]);
    try { checkoutUrl = new URL(checkoutUrl).toString(); } catch { checkoutUrl = ""; }
    const price = typeof o["price_usd"] === "number" && Number.isFinite(o["price_usd"]) ? Math.max(0, Math.round(o["price_usd"])) : 0;
    const plan = clean(o["plan"], "Pro");
    const altRaw = Array.isArray(o["alternatives"]) ? o["alternatives"] : [];
    const alternatives = altRaw
      .filter((a): a is Record<string, unknown> => typeof a === "object" && a !== null)
      .slice(0, 3)
      .map((a) => ({ toolName: clean(a["tool_name"], "?"), why: clean(a["why"]) }))
      .filter((a) => a.toolName !== "?");
    return {
      toolName,
      category: clean(o["category"], "SaaS tool"),
      checkoutUrl,
      plan,
      why: clean(o["why"]),
      alternatives,
      hasMcp: o["has_mcp"] === true,
      buySku: `saas:${slug(toolName)}-${slug(plan)}`,
      planPriceMinor: price * 100,
      planCurrency: "USD",
    };
  } catch {
    return null;
  }
}
